"""add addresses fias

Revision ID: 6cbef8cf23a2
Revises: 8dd77f592515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6cbef8cf23a2"
down_revision = "8dd77f592515"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("address", sa.Column("fias", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("address", "fias")
    # ### end Alembic commands ###
